# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in skippy.gemspec
gemspec

gem 'minitest', '~> 5.0'
gem 'rake', '~> 12.0'

group :test do
  gem 'simplecov', '~> 0.19.0'
end
